name: Publish package

on:
  repository_dispatch:
    types:
      - new_version
  workflow_dispatch:

env:
  PPA: ppa:fragoi/test

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.event.client_payload.version }}

  publish:
    needs: [version]
    runs-on: ubuntu-latest
    env:
      version: ${{ needs.version.outputs.version }}
    steps:
      - uses: fragoi/bash-actions@main

      - name: Download upstream source
        run: |
          upver=$(debUpver $version)
          downloadTag fragoi/hello-world v${upver} \
            hello-world_${upver}.orig.tar.gz

      - name: Download packaging info
        run: |
          downloadTag fragoi/hello-world-deb v${version} \
            hello-world_${version}.debian.tar.gz

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ env.PPA }}

      - name: List files
        run: ls -la
